module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("sales", [
      {
        id: 1,
        status: "RESERVED",
        userid: 2,
        invoiceid: 1,
        discountcodeid: null,
        paymentresource: "CASH",
        observation: "Observacion 1",
        subtotal: 100,
        iva: 12,
        totalsale: 112,
        saledate: new Date(),
        timecreated: new Date(),
      },
      {
        id: 2,
        status: "PENDING",
        userid: 2,
        invoiceid: 1,
        discountcodeid: null,
        paymentresource: "CASH",
        observation: "Observacion 2",
        subtotal: 100,
        iva: 12,
        totalsale: 112,
        saledate: new Date(),
        timecreated: new Date(),
      },
      {
        id: 3,
        status: "REJECTED",
        userid: 2,
        invoiceid: 2,
        discountcodeid: null,
        paymentresource: "PAYCHECK",
        observation: "Observacion 2",
        subtotal: 100,
        iva: 12,
        totalsale: 112,
        saledate: new Date(),
        timecreated: new Date(),
      },
      {
        id: 4,
        status: "PAID",
        userid: 2,
        invoiceid: 2,
        discountcodeid: 1,
        paymentresource: "CREDIT_CARD",
        observation: "Observacion 4",
        subtotal: 100,
        iva: 12,
        totalsale: 112,
        saledate: new Date(),
        timecreated: new Date(),
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("sales", null, {});
  }
};
